language: c++

os:
  - osx

compiler:
  - clang
  - gcc

before_install:
    - brew update && brew install opusfile libvorbis freetype flac physfs dumb theora enet;

env:
  - WANT_SHADERS_GL=on
  - WANT_SHADERS_GL=off

before_script:
  - mkdir build
  - cd build

script:
    - |
      cmake .. -DWANT_SHADERS_GL=$WANT_SHADERS_GL -G Xcode
      xcodebuild

notifications:
  irc:
    channels:
      - "irc.freenode.org#allegro-dev"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
