version: 1.0.{build}
clone_depth: 5

install:
  - mkdir deps
  - mkdir deps\include
  - mkdir deps\lib
  - nuget install freetype -OutputDirectory deps -ExcludeVersion
  - tree deps
  - ps: move deps\freetype\build\native\include\* deps\include -force
  - ps: move deps\freetype\build\native\lib\Win32\v110\static\Release\freetype246.lib deps\lib\freetype.lib -force
  - tree deps

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config RelWithDebInfo

test_script:
  - tree tests
  - tests\RelWithDebInfo\test_driver ..\tests\test_prim.ini > out.txt
  - type out.txt
